# Generated by Django 5.2.5 on 2025-10-22 19:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_vommetnt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vommetnt',
            new_name='Comment',
        ),
    ]
