# Generated by Django 5.2.5 on 2025-10-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_rename_vommetnt_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='vody',
            new_name='body',
        ),
    ]
