# Generated by Django 5.2.5 on 2025-10-26 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_comment_options_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='parent_post',
        ),
        migrations.AddField(
            model_name='reply',
            name='parent_comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment'),
            preserve_default=False,
        ),
    ]
